version: '3.8'

services:
  bonetto-backend:
    container_name: bonetto-backend
    build: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "5001:5001"
    networks:
      - bonetto-net

  bonetto-frontend:
    container_name: bonetto-frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - bonetto-backend
    networks:
      - bonetto-net

networks:
  bonetto-net:
    driver: bridge
